name       : rhythmbox-alternative-toolbar
version    : 0.18.2
release    : 10
source     :
    - https://github.com/fossfreedom/alternative-toolbar/archive/v0.18.2.tar.gz : 6f626ec96e89ba7347bbd5c538a1bcbc5318fbb2e3832d3ce2ddb38172fd77ba
license    : GPL-3.0-or-later
component  : desktop
summary    : Enhanced play controls and interface for Rhythmbox
description: |
    Replace the Rhythmbox large toolbar with a Client-Side Decorated or Compact toolbar which can be hidden.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(rhythmbox)
rundeps    :
    - rhythmbox
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-Solus-Defaults.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
