name       : rhythmbox-alternative-toolbar
version    : 0.17.4
release    : 6
source     :
    - https://github.com/fossfreedom/alternative-toolbar/archive/v0.17.4.tar.gz : 34acc619488977aaf92180256cda5b6709f9a8c63ddec1d404f70c9679ee64d8
license    : GPL-3.0
component  : desktop
summary    : Enhanced play controls and interface for Rhythmbox
description: |
    Replace the Rhythmbox large toolbar with a Client-Side Decorated or Compact toolbar which can be hidden.
rundeps    :
    - rhythmbox
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(rhythmbox)
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-Solus-Defaults.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
