name       : rhythmbox-alternative-toolbar
version    : 0.18.4
release    : 12
source     :
    - https://github.com/fossfreedom/alternative-toolbar/archive/v0.18.4.tar.gz : b6987ddc2f633f77edb930dc5fc421c10fb0f4510f4105af27f246af592cceaf
license    : GPL-3.0-or-later
component  : desktop
summary    : Enhanced play controls and interface for Rhythmbox
description: |
    Replace the Rhythmbox large toolbar with a Client-Side Decorated or Compact toolbar which can be hidden.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(rhythmbox)
rundeps    :
    - rhythmbox
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-Solus-Defaults.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
