name       : rhythmbox-alternative-toolbar
version    : 0.20.2
release    : 16
source     :
    - https://github.com/fossfreedom/alternative-toolbar/releases/download/v0.20.2/alternative-toolbar-0.20.2.tar.xz : f4eb7ebc6223f542652c74a8d4e16c99f8c03d60cb6ed848624065d5793b8df3
homepage   : https://github.com/fossfreedom/alternative-toolbar/
license    : GPL-3.0-or-later
component  : desktop
summary    : Enhanced play controls and interface for Rhythmbox
description: |
    Replace the Rhythmbox large toolbar with a Client-Side Decorated or Compact toolbar which can be hidden.
builddeps  :
    - pkgconfig(keybinder-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(rhythmbox)
rundeps    :
    - rhythmbox
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-Solus-Defaults.patch
    %configure
build      : |
    %make
install    : |
    %make_install
